import { Kit, ActivityType, AddOn, AddOnCategory, PriceType } from './types';

export const KITS: Kit[] = [
  {
    id: 'solo-duo',
    name: 'SOLO/DUO TRIP',
    price: '₹1500 per night',
    description: 'Perfect for 1-2 adventurers, lightweight and essential.',
    items: [
      '2-Person Tent',
      '2 Sleeping bags + mats',
      '1 Lantern + headlamp',
      '1 Portable stove + gas canister',
      'Basic cookware',
      'Spice mini-pack',
      '5L water container',
      'First-aid pouch',
      'Backpack (40L)',
    ],
    imageUrl: 'https://koa.com/blog/images/tips-for-solo-campers.jpg?preset=heroimagecropped',
    activityType: [ActivityType.CAMPING, ActivityType.TREKKING],
    features: ['Lightweight & Compact', 'All Essentials Included', 'Perfect for Backpacking'],
  },
  {
    id: 'family-friends-4',
    name: 'FAMILY/FRIENDS TRIP (4 PEOPLE)',
    price: '₹3000 per night',
    description: 'Everything you need for a memorable group outing.',
    items: [
      '4-Person Tent (with rainfly & tarp)',
      '4 Sleeping bags + mats + pillows',
      'Camping table + 4 foldable chairs',
      'Cooking set for four',
      'Portable gas stove + 2 cylinders',
      'Spice box (basic Indian spices)',
      'Cooler box (ice storage)',
      'Lantern + 2 headlamps',
      'First-aid kit',
      'Picnic mat',
      'Backpack (60L)',
    ],
    imageUrl: 'https://www.shutterstock.com/image-photo/happy-family-camping-tent-near-260nw-1096054364.jpg',
    activityType: [ActivityType.CAMPING],
    features: ['Spacious 4-Person Tent', 'Comfortable Seating', 'Complete Cooking Setup'],
  },
  {
    id: 'adventure-group-6',
    name: 'ADVENTURE GROUP KIT (6 PEOPLE)',
    price: '₹4500 per night',
    description: 'For larger groups ready to take on the wild.',
    items: [
      '6-Person Tent (waterproof, ventilated)',
      '6 Sleeping bags + mats',
      '2 Stoves + gas canisters',
      'Large cookware set',
      '6 Plates + spoons + mugs',
      'Spice + oil mini-pack',
      '20L collapsible water container',
      'Lantern + 3 headlamps',
      'First-aid box (full set)',
      '1 Rope + multitool + knife',
      '2 Backpacks (70L shared)',
    ],
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR87A6dVW_VotEamUKa_G5JQsDG3HabdoixYA&s',
    activityType: [ActivityType.CAMPING, ActivityType.TREKKING],
    features: ['Heavy-Duty & Waterproof', 'Large Group Cookware', 'Safety Gear Included'],
  },
  {
    id: 'luxury-kit-2-3',
    name: 'LUXURY KIT (2-3 PEOPLE)',
    price: '₹5000 per night',
    description: 'Experience the outdoors with ultimate comfort and style.',
    items: [
      'Spacious 3-Person Tent (high ceiling)',
      'Inflatable mattress + pump + cozy blankets',
      '2 Premium sleeping bags',
      '2 Recliner camping chairs + mini table',
      'LED Lantern + fairy lights',
      'Stove + cookware + spice box',
      'Cooler box (with ice packs)',
      'Coffee/tea setup',
      'Picnic mat & Bluetooth speaker',
    ],
    imageUrl: 'https://tutc.com/images/packages/home/1.jpg',
    activityType: [ActivityType.CAMPING, ActivityType.EVENT],
    features: ['Premium Comfort', 'Ambiance Lighting', 'Entertainment Options'],
  },
  {
    id: 'corporate-school-10-12',
    name: 'CORPORATE/SCHOOL KIT (10-12 PEOPLE)',
    price: '₹10000 per night',
    description: 'Perfect for team-building, educational trips, or large events.',
    items: [
      '2 Large Family Tents (6-person each)',
      '10–12 Sleeping bags + mats',
      '3 Stoves + bulk cookware set',
      'Dining setup (tables + chairs)',
      '3 Lanterns + 4 headlamps',
      'Bulk spice & condiment kit',
      'Large cooler box',
      'First-aid + insect repellent pack',
      'Sports set (volleyball, frisbee)',
    ],
    imageUrl: 'https://arschoolcamp.com/wp-content/uploads/2023/06/snow-monk-2.jpg',
    activityType: [ActivityType.CAMPING, ActivityType.EVENT],
    features: ['Bulk & Group Ready', 'Team Activities Included', 'Hassle-Free Setup'],
  },
  {
    id: 'beach-kit-2-4',
    name: 'BEACH CAMP KIT (2-4 PEOPLE)',
    price: '₹2500 per night',
    description: 'Sun, sand, and stars. The ultimate beach getaway.',
    items: [
      'Beach tent',
      'Beach mats + foldable chairs',
      'Cooler box',
      'Waterproof dry bag',
      'Snorkeling set / water toys',
      'Bluetooth speaker',
      'Sand-resistant lantern',
      'First-aid + seasickness tablets',
    ],
    imageUrl: 'https://d26dp53kz39178.cloudfront.net/media/uploads/products/Camping-37_OQnqq20.jpg',
    activityType: [ActivityType.BEACH],
    features: ['Sand & Sun Ready', 'Waterproof Gear', 'Fun & Relaxation'],
  },
  {
    id: 'trekking-forest-2-3',
    name: 'TREKKING / FOREST KIT (2-3 PEOPLE)',
    price: '₹2200 per night',
    description: 'Lightweight and durable, your perfect companion for long treks.',
    items: [
      'Ultralight trekking tent',
      'Lightweight, compact sleeping bags',
      'Trekking poles + rope + carabiners',
      'Stove + compact cookware',
      'Water filter / purifier tablets',
      'Insect repellent + mosquito net',
      'Multi-tool / knife',
      'Solar power bank',
      'First-aid (with blister pads)',
    ],
    imageUrl: 'https://visithimalayastrek.com/uploads/photos/1/Kanchenjunga-Region/Kanchenjunga-Base-Camp-Trekking-In-Nepal.jpg',
    activityType: [ActivityType.TREKKING],
    features: ['Ultralight & Durable', 'Essential Survival Tools', 'Off-Grid Power'],
  },
  {
    id: 'winter-snow-2-4',
    name: 'WINTER / SNOW KIT (2-4 PEOPLE)',
    price: '₹4500 per night',
    description: 'Stay warm and cozy while exploring snowy landscapes.',
    items: [
      'Insulated 4-season tent',
      '-10°C sleeping bags',
      'Inflatable mattress + thermal mats',
      'Portable heater (safe for camping)',
      'Thermal cookware + thermos flasks',
      'Extra blankets, gloves & socks',
      'Cold-resistant battery lantern',
      'First-aid + frostbite ointments',
    ],
    imageUrl: 'https://static1.squarespace.com/static/650288a7a9c25d20636249f7/t/65680bf8b85c4e0e813c4b2e/1701317627509/K7-Snowcamp.jpg?format=1500w',
    activityType: [ActivityType.WINTER, ActivityType.CAMPING],
    features: ['-10°C Warmth Rated', 'Insulated 4-Season Tent', 'Portable Heater Included'],
  },
  {
    id: 'event-celebration-2-6',
    name: 'EVENT / CELEBRATION KIT (2-6 PEOPLE)',
    price: '₹6000 per night',
    description: 'Celebrate special occasions outdoors in style.',
    items: [
      'Bell tent / luxury tent setup',
      'Fairy lights + lanterns + rugs',
      'Recliner chairs + coffee table',
      'Speaker + games set',
      'Picnic basket + cooler box',
      'Cozy blankets & cushions',
      'Polaroid camera (add-on)',
      'First-aid kit',
    ],
    imageUrl: 'https://i.pinimg.com/736x/07/3c/03/073c03a7a85a42e1f106a4bff400ed31.jpg',
    activityType: [ActivityType.EVENT],
    features: ['Stylish Bell Tent', 'Celebration Ambiance', 'Picture-Perfect Setup'],
  },
  {
    id: 'lakeside-camping-2-4',
    name: 'LAKESIDE CAMPING KIT (2-4 PEOPLE)',
    price: '₹2500 per night',
    description: 'Enjoy serene views and waterside activities.',
    items: [
      'Waterproof tent with tarp',
      'Sleeping bags + mats',
      'Life jackets (optional add-on)',
      'Portable stove + cookware',
      'Fishing kit (optional)',
      'Waterproof dry bags',
      'Bug repellent kit',
      'First-aid kit',
    ],
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0oTBptDUFXIgnmL9_FpOU0mbI-kYvg-KeRA&s',
    activityType: [ActivityType.LAKESIDE, ActivityType.CAMPING],
    features: ['Waterside Ready', 'Fishing & Safety Gear', 'Enhanced Bug Protection'],
  },
];

export const ADD_ONS: AddOn[] = [
  // Comfort & Utility
  { id: 'hand-vacuum', name: 'Hand vacuum', price: 350, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'privacy-tent', name: 'Foldable privacy tent', price: 150, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'storage-box', name: 'Storage box (pack of 2)', price: 120, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'used-clothes-storage', name: 'Used clothes storage (pack of 2)', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'trash-cans', name: 'Trash cans', price: 80, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'wet-wipes', name: 'Wet wipes', price: 50, priceType: PriceType.PER_ITEM, description: 'per pack', category: AddOnCategory.COMFORT_UTILITY },
  { id: 'candles', name: 'Candles', price: 20, priceType: PriceType.PER_ITEM, description: 'per pack', category: AddOnCategory.COMFORT_UTILITY },
  { id: 'umbrella', name: 'Umbrella', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'wind-shield', name: 'Wind shield', price: 150, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'hot-pack', name: 'Hot pack', price: 120, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  { id: 'mosquito-net', name: 'Mosquito net', price: 120, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COMFORT_UTILITY },
  
  // Lighting & Ambience
  { id: 'wish-lamp', name: 'Wish lamp (pack 4)', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.LIGHTING_AMBIENCE },
  { id: 'fairy-lights', name: 'Fairy lights', price: 80, priceType: PriceType.PER_NIGHT, category: AddOnCategory.LIGHTING_AMBIENCE },
  { id: 'radium-bands', name: 'Radium bands (pack 100)', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.LIGHTING_AMBIENCE },
  
  // Entertainment & Tech
  { id: 'projector', name: 'Projector', price: 700, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'instant-camera', name: 'Instant camera', price: 600, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'bluetooth-speaker', name: 'Bluetooth speaker', price: 300, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'telescope', name: 'Telescope', price: 250, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'binoculars', name: 'Binoculars', price: 150, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'selfie-stick', name: 'Selfie stick', price: 80, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'announcement-mic', name: 'Announcement mic', price: 200, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'walkie-talkies', name: 'Walkie talkies (set of 6)', price: 600, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'power-bank', name: 'Power bank', price: 180, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  { id: 'portable-generator', name: 'Portable Generator', price: 900, priceType: PriceType.PER_NIGHT, category: AddOnCategory.ENTERTAINMENT_TECH },
  
  // Cooking & Food
  { id: 'bbq-grill', name: 'BBQ grill', price: 300, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COOKING_FOOD },
  { id: 'aprons', name: 'Aprons', price: 50, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COOKING_FOOD },
  { id: 'beach-kit', name: 'Beach kit', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.COOKING_FOOD },
  
  // Safety & Health
  { id: 'ear-plugs', name: 'Ear plugs', price: 30, priceType: PriceType.PER_ITEM, description: 'per pair', category: AddOnCategory.SAFETY_HEALTH },
  { id: 'eye-masks', name: 'Eye masks', price: 50, priceType: PriceType.PER_ITEM, description: 'each', category: AddOnCategory.SAFETY_HEALTH },
  { id: 'mosquito-repellent', name: 'Mosquito repellent', price: 30, priceType: PriceType.PER_ITEM, description: 'per bottle', category: AddOnCategory.SAFETY_HEALTH },
  { id: 'vomit-bags', name: 'Vomit bags', price: 20, priceType: PriceType.PER_ITEM, description: 'each', category: AddOnCategory.SAFETY_HEALTH },
  { id: 'rope-clips', name: 'Rope with clips', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.SAFETY_HEALTH },
  { id: 'compass', name: 'Compass', price: 50, priceType: PriceType.PER_NIGHT, category: AddOnCategory.SAFETY_HEALTH },

  // Games & Fun
  { id: 'skillmatics', name: 'Skillmatics', price: 150, priceType: PriceType.PER_NIGHT, category: AddOnCategory.GAMES_FUN },
  { id: 'brainvita', name: 'Brainvita', price: 100, priceType: PriceType.PER_NIGHT, category: AddOnCategory.GAMES_FUN },
  { id: 'jenga', name: 'Jenga', price: 120, priceType: PriceType.PER_NIGHT, category: AddOnCategory.GAMES_FUN },
  { id: 'uno-cards', name: 'UNO cards', price: 80, priceType: PriceType.PER_NIGHT, category: AddOnCategory.GAMES_FUN },
  { id: 'playing-cards', name: 'Playing cards', price: 50, priceType: PriceType.PER_NIGHT, category: AddOnCategory.GAMES_FUN },
  { id: 'rackets', name: 'Rackets (pair)', price: 150, priceType: PriceType.PER_NIGHT, category: AddOnCategory.GAMES_FUN },
];